In [1]:
import pandas as pd

In [2]:
pip install langdetect

Requirement already satisfied: langdetect in /Users/izaiaszacca/anaconda3/lib/python3.11/site-packages (1.0.9)
Requirement already satisfied: six in /Users/izaiaszacca/anaconda3/lib/python3.11/site-packages (from langdetect) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
f = pd.read_csv("file123.csv")

In [4]:
f.head(12)

,reviews,reviewer,starRating,createTime,updateTime,name,comment,displayName,reviewer_name,review_id
0,{'reviewer': {'displayName': 'Virginia Malék M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'reviewer': {'displayName': 'Edson ITD'}, 'st...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'reviewer': {'displayName': 'Alessandra Santo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'reviewer': {'displayName': 'Marcos Scudeler'...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'reviewer': {'displayName': 'Ailton Dos Santo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'reviewer': {'displayName': 'Luiz Cardozo'}, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,{'reviewer': {'displayName': 'Tony Leandro de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,{'reviewer': {'displayName': 'novo canal link ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'reviewer': {'displayName': 'Favero Neto'}, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,{'reviewer': {'displayName': 'Monica Alves M. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{'reviewer': {'displayName': 'Paulo Veiga'}, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{'reviewer': {'displayName': 'Lucas Ponce'}, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   reviews        20 non-null     object
 1   reviewer       56 non-null     object
 2   starRating     56 non-null     object
 3   createTime     56 non-null     object
 4   updateTime     56 non-null     object
 5   name           56 non-null     object
 6   comment        29 non-null     object
 7   displayName    31 non-null     object
 8   reviewer_name  31 non-null     object
 9   review_id      31 non-null     object
dtypes: object(10)
memory usage: 6.1+ KB

In [8]:
import pandas as pd
from langdetect import detect

# Assuming you have a DataFrame df with a column named 'comment'
df = pd.DataFrame({'comment': f["comment"]})
    
    
# Function to detect language
def detect_language(text):
    try:
        lang = detect(text)
        return lang
    except:
        return 'unknown'

# Apply language detection to each row in the 'comment' column
df['Language'] = df['comment'].apply(detect_language)

# Separate into different columns based on language
df_english = df[df['Language'] == 'en']
df_portuguese = df[df['Language'] == 'pt']

# Drop the 'Language' column if you no longer need it
df_english = df_english.drop(columns=['Language'])
df_portuguese = df_portuguese.drop(columns=['Language'])

# Display the results
print("English Texts:")
print(df_english['comment'].values)

print("\nPortuguese Texts:")
print(df_portuguese['comment'].values)

English Texts:
['(Translated by Google) Camping with a family atmosphere and good structure, with swimming pools and courts. Grassy camping area with structure for washing dishes. Simple bathrooms but are cleaned daily. It also has cottages.\n\n(Original)\nCamping com ambiente familiar e boa estrutura, possuindo piscinas e quadras. Área de acampamento gramada e com estrutura para lavar pratos. Banheiros simples porém são limpos diariamente. Também possui chalés.'
 "(Translated by Google) The best camping I've ever been to! Very cool structure in a family and fun environment. I recommend it to everyone! Super close to the city center. I've been going there for years!\n\n(Original)\nO melhor camping que já fui! Estrutura muito legal em um ambiente familiar e divertido. Recomendo a todos! Super perto do centro da cidade. Já frequento a anos!"
 '(Translated by Google) Very good\n\n(Original)\nMuito bom'
 '(Translated by Google) Excellent service, maximum comfort, reasonable price.\n\n(Original)\nAtendimento excelente, máximo conforto, preço razoável.'
 '(Translated by Google) Best infrastructure for campers in the region, it also has rooms and a restaurant\n\n(Original)\nMelhor infra pro campista da região, além disso tem aptos e restaurante'
 '(Translated by Google) Very family place. Always very pleasant and understanding service. Calm place. Breakfast and lunch made with quality and lots of affection. Every detail is thought out for the visitor. Control of the number of people per day guarantees peace of mind. I have already used the camping and this time in the chalet. I keep coming back.\n\n(Original)\nLugar muito família. Atendimento sempre muito agradável e compreensivo. Lugar calma. Café da manhã e almoço feitos c qualidade e muito carinho. Cada detalhe é pensado p o visitante. Controle de quantidade de pessoas por dia garante o sossego. Já usei o camping e dessa vez no chalé. Continuo sempre a voltar.'
 '(Translated by Google) Great place to camp, or stay in great cabins with family or friends. Place with restaurant and good structure next to nature.\n\n(Original)\nÓtimo local para acampar, ou ficar em ótimos chalés com a família ou amigos. Local com restaurante e boa estrutura junto a natureza.'
 '(Translated by Google) Excellent\n\n(Original)\nÓtimo'
 '(Translated by Google) Crowded!! It had everything to be good. Dirty pool.\n\n(Original)\nLotado!! Tinha tudo pra ser bom. Piscina suja.'
 'Top'
 '(Translated by Google) Great facilities, good trails, restaurant, etc.\n\n(Original)\nÓtimas instalações, boas trilhas, restaurante, etc'
 '(Translated by Google) The atmosphere is very familiar, the food is very delicious and the chalets are cozy.\n\n(Original)\nO ambiente é bem familiar,a comida é muito gostosa e os chalés aconchegantes'
 '(Translated by Google) We liked a lot\n\n(Original)\nGostamos muito'
 '(Translated by Google) Ideal place to rest.\n\n(Original)\nLugar ideal para descansar.'
 "(Translated by Google) I based on the reviews to choose the inn, but I didn't have a good experience. Camping is on a hill and the reserved chalet was like we were inside a hole. Old furniture and no kitchen accessories. Spider web in several places. Television only picked up one channel. Poor quality rented linen and stained pillows.\nI went at night and the playground and the pool were in the dark. Poor lighting. Impossible to use. With a small child who needs an attraction, I don't recommend it. You can't even use velotrol at the campsite.\nPositive point for the service of the staff. They were prompt in reimbursing us.\n\n(Original)\nMe baseei nas avaliações pra escolher a pousada, mas não tive boa experiência. Camping fica num morro e o chalé reservado era como se nós estivéssemos dentro de um buraco. Móveis velhos e nenhum acessório de cozinha. Teia de aranha em vários lugares. Televisão só pegava um canal. Roupa de cama alugada de má qualidade e travesseiros manchados.\nFui a noite e o playground e a piscina ficam no escuro. Iluminação precária. Impossível de usar. Com criança pequena que precisa de um atrativo, não recomendo. Nem velotrol dá pra usar no camping.\nPonto positivo pro atendimento dos funcionários. Foram prontos em nos reembolsar."
 '(Translated by Google) Cozy....I really like the place and the staff!!! Very good service and great food!\n\n(Original)\nAconchegante....gosto muito do local e dos funcionários!!! Atendimento muito bom e comida TB!'
 '(Translated by Google) Excellent service, staff always very attentive\n\n(Original)\nExcelente atendimento, pessoal sempre bem atencioso'
 "(Translated by Google) It's been great.\n\n(Original)\nEstá sendo ótima."
 '(Translated by Google) This place is good, you just have to improve the chalet\n\n(Original)\nEsse lugar e bom só tem que melhorar o chalé'
 '(Translated by Google) Excellent. Well family.\n\n(Original)\nOtimo. Bem familia.'
 '(Translated by Google) Very good for camping or renting a chalet\n\n(Original)\nMuito bom para acampar ou alugar chalé'
 '(Translated by Google) Family atmosphere. Great place to rest\n\n(Original)\nAmbiente familiar. Ótimo local para descanso'
 '(Translated by Google) Great food.. cozy place\n\n(Original)\nComida ótima.. lugar aconchegante'
 '(Translated by Google) Just wonderful. Good price, good restaurant too. Ideal for those who like to camp. Easy access. I recommend.\n\n(Original)\nSimplesmente maravilhoso. Preço bom, restaurante bom também. Ideal para quem gosta de acampar. Fácil acesso. Recomendo.'
 '(Translated by Google) Very good\n\n(Original)\nMuito boa'
 '(Translated by Google) The best\n\n(Original)\nO melhor'
 '(Translated by Google) Very quiet and wonderful family place\n\n(Original)\nLocal muito tranquilo e familiar maravilhoso']

Portuguese Texts:
[]

In [17]:
df_english.head()

                                              comment Language
25  (Translated by Google) Camping with a family a...       en
28  (Translated by Google) The best camping I've e...       en
29  (Translated by Google) Very good\n\n(Original)...       en
30  (Translated by Google) Excellent service, maxi...       en
31  (Translated by Google) Best infrastructure for...       en

In [21]:
#df_english.iloc[28]
df_english["comment"].iloc[1]

"(Translated by Google) The best camping I've ever been to! Very cool structure in a family and fun environment. I recommend it to everyone! Super close to the city center. I've been going there for years!\n\n(Original)\nO melhor camping que já fui! Estrutura muito legal em um ambiente familiar e divertido. Recomendo a todos! Super perto do centro da cidade. Já frequento a anos!"

In [9]:
df.head()

  comment Language
0     NaN  unknown
1     NaN  unknown
2     NaN  unknown
3     NaN  unknown
4     NaN  unknown

In [10]:
import pandas as pd
from langdetect import detect

# Assuming you have a DataFrame df with a column named 'comment'
df = pd.DataFrame({'comment': f["comment"]})
    
    
# Function to detect language
def detect_language(text):
    try:
        lang = detect(text)
        return lang
    except:
        return 'unknown'

# Apply language detection to each row in the 'comment' column
f['Language'] = f['comment'].apply(detect_language)

# Separate into different columns based on language
f['English_Text'] = f[f['Language'] == 'en']['comment']
f['Portuguese_Text'] = f[f['Language'] == 'pt']['comment']

# Drop the 'Language' column if you no longer need it
f = f.drop(columns=['Language'])

# Display the results
print("DataFrame with English and Portuguese Texts:")
print(f)

DataFrame with English and Portuguese Texts:
                                              reviews  \
0   {'reviewer': {'displayName': 'Virginia Malék M...
1   {'reviewer': {'displayName': 'Edson ITD'}, 'st...
2   {'reviewer': {'displayName': 'Alessandra Santo...
3   {'reviewer': {'displayName': 'Marcos Scudeler'...
4   {'reviewer': {'displayName': 'Ailton Dos Santo...
..                                                ...
71                                                NaN
72                                                NaN
73                                                NaN
74                                                NaN
75                                                NaN

                                       reviewer starRating  \
0                                           NaN        NaN
1                                           NaN        NaN
2                                           NaN        NaN
3                                           NaN        NaN
4                                           NaN        NaN
..                                          ...        ...
71                {'displayName': 'Matheus SB'}       FIVE
72          {'displayName': 'Eliezer Monteiro'}       FIVE
73           {'displayName': 'Lucas Gasparini'}       FIVE
74              {'displayName': 'wagner diniz'}       FIVE
75  {'displayName': 'Paulo Sergio Costa Braga'}       FIVE

                  createTime                updateTime  \
0                        NaN                       NaN
1                        NaN                       NaN
2                        NaN                       NaN
3                        NaN                       NaN
4                        NaN                       NaN
..                       ...                       ...
71  2018-02-28T16:13:13.279Z  2018-02-28T16:13:30.711Z
72  2018-01-21T17:49:56.901Z  2018-02-27T03:02:33.005Z
73  2018-02-26T15:46:56.876Z  2018-02-26T15:47:54.784Z
74  2018-02-26T11:59:53.396Z  2018-02-26T12:00:00.704Z
75  2018-02-26T11:49:25.750Z  2018-02-26T11:50:19.695Z

                                                 name  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
..                                                ...
71  accounts/113838515205835963900/locations/41527...
72  accounts/113838515205835963900/locations/41527...
73  accounts/113838515205835963900/locations/41527...
74  accounts/113838515205835963900/locations/41527...
75  accounts/113838515205835963900/locations/41527...

                                              comment  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
..                                                ...
71  (Translated by Google) Great food.. cozy place...
72  (Translated by Google) Just wonderful. Good pr...
73  (Translated by Google) Very good\n\n(Original)...
74  (Translated by Google) The best\n\n(Original)\...
75  (Translated by Google) Very quiet and wonderfu...

                 displayName             reviewer_name  \
0                        NaN                       NaN
1                        NaN                       NaN
2                        NaN                       NaN
3                        NaN                       NaN
4                        NaN                       NaN
..                       ...                       ...
71                Matheus SB                Matheus SB
72          Eliezer Monteiro          Eliezer Monteiro
73           Lucas Gasparini           Lucas Gasparini
74              wagner diniz              wagner diniz
75  Paulo Sergio Costa Braga  Paulo Sergio Costa Braga

                               review_id  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
..                                   ...
71   ChZDSUhNMG9nS0VJQ0FnSUN3OE02Y0hBEAE
72   ChZDSUhNMG9nS0VJQ0FnSUNnNFA2VUNREAE
73  ChdDSUhNMG9nS0VJQ0FnSURBLTk2eHVRRRAB
74  ChdDSUhNMG9nS0VJQ0FnSUNZaU9idHhRRRAB
75   ChZDSUhNMG9nS0VJQ0FnSURBaU9td09BEAE

                                         English_Text Portuguese_Text
0                                                 NaN             NaN
1                                                 NaN             NaN
2                                                 NaN             NaN
3                                                 NaN             NaN
4                                                 NaN             NaN
..                                                ...             ...
71  (Translated by Google) Great food.. cozy place...             NaN
72  (Translated by Google) Just wonderful. Good pr...             NaN
73  (Translated by Google) Very good\n\n(Original)...             NaN
74  (Translated by Google) The best\n\n(Original)\...             NaN
75  (Translated by Google) Very quiet and wonderfu...             NaN

[76 rows x 12 columns]

In [13]:
f.head(50)

,reviews,reviewer,starRating,createTime,updateTime,name,comment,displayName,reviewer_name,review_id,English_Text,Portuguese_Text
0,{'reviewer': {'displayName': 'Virginia Malék M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'reviewer': {'displayName': 'Edson ITD'}, 'st...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'reviewer': {'displayName': 'Alessandra Santo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'reviewer': {'displayName': 'Marcos Scudeler'...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'reviewer': {'displayName': 'Ailton Dos Santo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'reviewer': {'displayName': 'Luiz Cardozo'}, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,{'reviewer': {'displayName': 'Tony Leandro de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,{'reviewer': {'displayName': 'novo canal link ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'reviewer': {'displayName': 'Favero Neto'}, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,{'reviewer': {'displayName': 'Monica Alves M. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{'reviewer': {'displayName': 'Paulo Veiga'}, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{'reviewer': {'displayName': 'Lucas Ponce'}, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"{'reviewer': {'displayName': 'Carlos Magno'}, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,{'reviewer': {'displayName': 'Cleyton Andrade'...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,{'reviewer': {'displayName': 'Ana Paula Talhar...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,{'reviewer': {'displayName': 'Reinaldo Soares ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"{'reviewer': {'displayName': 'Fael Faul'}, 'st...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,{'reviewer': {'displayName': 'Eliana Azevedo'}...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"{'reviewer': {'displayName': 'Silvia Aquino'},...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,{'reviewer': {'displayName': 'Marcelo o empree...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,{'displayName': 'Érica Teixeira'},FOUR,2018-03-11T12:26:43.805Z,2018-03-11T12:26:43.805Z,accounts/113838515205835963900/locations/41527...,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,{'displayName': 'Fernando Posso'},FIVE,2018-03-11T11:55:40.211Z,2018-03-11T11:55:40.211Z,accounts/113838515205835963900/locations/41527...,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,{'displayName': 'michele silva'},FOUR,2018-03-10T20:38:03.083Z,2018-03-10T20:38:03.083Z,accounts/113838515205835963900/locations/41527...,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,{'displayName': 'Ana Carolina Cordeiro'},FOUR,2018-03-10T11:45:18.264Z,2018-03-10T11:45:18.264Z,accounts/113838515205835963900/locations/41527...,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,{'displayName': 'Mariana Meneguim Wonraht'},FOUR,2018-03-10T10:55:28.512Z,2018-03-10T10:55:28.512Z,accounts/113838515205835963900/locations/41527...,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,{'displayName': 'Edson Ogata'},FOUR,2017-05-26T22:07:31.680Z,2017-07-23T04:21:41.602Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Camping with a family a...,Edson Ogata,Edson Ogata,ChdDSUhNMG9nS0VJQ0FnSUNRajZ2WTlRRRAB,(Translated by Google) Camping with a family a...,NaN
26,NaN,{'displayName': 'Paulo Thunder'},FIVE,2017-07-21T05:55:14.115Z,2017-07-21T05:55:14.115Z,accounts/113838515205835963900/locations/41527...,NaN,Paulo Thunder,Paulo Thunder,ChZDSUhNMG9nS0VJQ0FnSUNRNWFfUVJ3EAE,NaN,NaN
27,NaN,{'displayName': 'Gui e rafa Filios'},FOUR,2017-07-18T21:06:30.581Z,2017-07-18T21:06:30.581Z,accounts/113838515205835963900/locations/41527...,NaN,Gui e rafa Filios,Gui e rafa Filios,ChZDSUhNMG9nS0VJQ0FnSUNnOTlyNEV3EAE,NaN,NaN
28,NaN,{'displayName': 'Dayana Godeguesi Ayres'},FIVE,2017-07-17T23:33:34.267Z,2017-07-17T23:33:34.267Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) The best camping I've e...,Dayana Godeguesi Ayres,Dayana Godeguesi Ayres,ChdDSUhNMG9nS0VJQ0FnSURBdjVTMF93RRAB,(Translated by Google) The best camping I've e...,NaN
29,NaN,{'displayName': 'Gabriel Souza Brito da Silva'},FIVE,2017-07-15T21:37:44.486Z,2017-07-15T21:37:44.486Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Very good\n\n(Original)...,Gabriel Souza Brito da Silva,Gabriel Souza Brito da Silva,ChdDSUhNMG9nS0VJQ0FnSURRbHNyZXlRRRAB,(Translated by Google) Very good\n\n(Original)...,NaN
30,NaN,{'displayName': 'Carol Severian'},FIVE,2017-07-14T21:32:45.424Z,2017-07-14T21:32:45.424Z,accounts/113838515205835963900/locations/41527...,"(Translated by Google) Excellent service, maxi...",Carol Severian,Carol Severian,ChdDSUhNMG9nS0VJQ0FnSUNndF9qeXR3RRAB,NaN,"(Translated by Google) Excellent service, maxi..."
31,NaN,{'displayName': 'Silverio Cavalli junior'},FIVE,2017-07-14T18:17:45.876Z,2017-07-14T18:18:29.689Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Best infrastructure for...,Silverio Cavalli junior,Silverio Cavalli junior,ChZDSUhNMG9nS0VJQ0FnSURBMllMRGFREAE,(Translated by Google) Best infrastructure for...,NaN
32,NaN,{'displayName': 'Cristina Affonso'},FIVE,2017-07-12T12:34:56.343Z,2017-07-12T12:39:10.125Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Very family place. Alwa...,Cristina Affonso,Cristina Affonso,ChdDSUhNMG9nS0VJQ0FnSUNBcEsyTmtRRRAB,(Translated by Google) Very family place. Alwa...,NaN
33,NaN,{'displayName': 'Jacky Feitoza'},FOUR,2017-07-10T07:22:13.565Z,2017-07-10T07:22:17.361Z,accounts/113838515205835963900/locations/41527...,NaN,Jacky Feitoza,Jacky Feitoza,ChZDSUhNMG9nS0VJQ0FnSUNnazQ2aWF3EAE,NaN,NaN
34,NaN,{'displayName': 'Walter Augusto Benatti'},FIVE,2017-07-09T17:55:46.588Z,2017-07-09T17:56:52.874Z,accounts/113838515205835963900/locations/41527...,"(Translated by Google) Great place to camp, or...",Walter Augusto Benatti,Walter Augusto Benatti,ChZDSUhNMG9nS0VJQ0FnSURBamFiX1lREAE,"(Translated by Google) Great place to camp, or...",NaN
35,NaN,{'displayName': 'Pedro Antonio Filho'},FIVE,2017-07-06T22:31:51.537Z,2017-07-06T22:31:51.537Z,accounts/113838515205835963900/locations/41527...,NaN,Pedro Antonio Filho,Pedro Antonio Filho,ChZDSUhNMG9nS0VJQ0FnSUN3eW92Q09BEAE,NaN,NaN
36,NaN,{'displayName': 'lucio nunes'},FIVE,2017-11-19T20:07:08.318Z,2017-11-19T20:07:08.318Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Excellent\n\n(Original)...,lucio nunes,lucio nunes,ChZDSUhNMG9nS0VJQ0FnSURROGNiME5BEAE,(Translated by Google) Excellent\n\n(Original)...,NaN
37,NaN,{'displayName': 'Felipe Souza'},TWO,2017-10-15T10:02:21.987Z,2017-11-19T12:12:37.904Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Crowded!! It had everyt...,Felipe Souza,Felipe Souza,ChdDSUhNMG9nS0VJQ0FnSUNBaDZMazlBRRAB,(Translated by Google) Crowded!! It had everyt...,NaN
38,NaN,{'displayName': 'Denis André Dellanava Martin'},FIVE,2017-11-16T21:37:53.212Z,2017-11-16T21:37:59.663Z,accounts/113838515205835963900/locations/41527...,Top,Denis André Dellanava Martin,Denis André Dellanava Martin,ChZDSUhNMG9nS0VJQ0FnSURBNHJyRlFBEAE,Top,NaN
39,NaN,{'displayName': 'Henrique Schroder'},FIVE,2017-11-14T00:34:39.487Z,2017-11-14T00:34:39.487Z,accounts/113838515205835963900/locations/41527...,"(Translated by Google) Great facilities, good ...",Henrique Schroder,Henrique Schroder,ChZDSUhNMG9nS0VJQ0FnSUNRdFBpYWVBEAE,"(Translated by Google) Great facilities, good ...",NaN
40,NaN,{'displayName': 'Raphaela Barzon'},FIVE,2017-11-10T18:17:35.231Z,2017-11-10T18:18:31.909Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) The atmosphere is very ...,Raphaela Barzon,Raphaela Barzon,ChdDSUhNMG9nS0VJQ0FnSUNnczlTeTVRRRAB,(Translated by Google) The atmosphere is very ...,NaN
41,NaN,{'displayName': 'Wolle B'},FOUR,2017-11-10T10:31:21.514Z,2017-11-10T10:31:21.514Z,accounts/113838515205835963900/locations/41527...,NaN,Wolle B,Wolle B,ChdDSUhNMG9nS0VJQ0FnSURnaHNiNnR3RRAB,NaN,NaN
42,NaN,{'displayName': 'Fabio Cunha'},FIVE,2017-11-09T21:05:11.121Z,2017-11-09T21:05:34.753Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) We liked a lot\n\n(Orig...,Fabio Cunha,Fabio Cunha,ChdDSUhNMG9nS0VJQ0FnSUNBcklDZHpRRRAB,(Translated by Google) We liked a lot\n\n(Orig...,NaN
43,NaN,{'displayName': 'Beatriz Machado Canedo'},FIVE,2017-11-09T19:02:36.324Z,2017-11-09T19:02:36.324Z,accounts/113838515205835963900/locations/41527...,NaN,Beatriz Machado Canedo,Beatriz Machado Canedo,ChdDSUhNMG9nS0VJQ0FnSUNBaGVfM19RRRAB,NaN,NaN
44,NaN,{'displayName': 'Glaucia Oliveira'},FIVE,2017-11-09T11:21:09.141Z,2017-11-09T11:21:09.141Z,accounts/113838515205835963900/locations/41527...,NaN,Glaucia Oliveira,Glaucia Oliveira,ChZDSUhNMG9nS0VJQ0FnSUNRaXVYUVhBEAE,NaN,NaN
45,NaN,{'displayName': 'Jorge de Souza'},FIVE,2017-11-09T09:09:35.026Z,2017-11-09T09:10:08.856Z,accounts/113838515205835963900/locations/41527...,"(Translated by Google) Family environment, exc...",NaN,NaN,NaN,NaN,NaN
46,NaN,{'displayName': 'Paulo Bertinelli'},FIVE,2017-11-08T14:51:38.767Z,2017-11-08T14:51:49.339Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Ideal place to rest.\n\...,NaN,NaN,NaN,(Translated by Google) Ideal place to rest.\n\...,NaN
47,NaN,{'displayName': 'Renata Sol S'},TWO,2017-11-03T20:57:49.779Z,2017-11-03T20:57:49.779Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) I based on the reviews ...,NaN,NaN,NaN,(Translated by Google) I based on the reviews ...,NaN
48,NaN,{'displayName': 'Paulo Sérgio Francisco de Jes...,ONE,2017-11-03T19:15:52.128Z,2017-11-03T19:15:52.128Z,accounts/113838515205835963900/locations/41527...,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,{'displayName': 'Elaina Fanchini'},FIVE,2017-11-03T17:57:17.154Z,2017-11-03T17:57:57.494Z,accounts/113838515205835963900/locations/41527...,(Translated by Google) Cozy....I really like t...,NaN,NaN,NaN,(Translated by Google) Cozy....I really like t...,NaN

In [16]:
f["English_Text"].iloc[46]

'(Translated by Google) Ideal place to rest.\n\n(Original)\nLugar ideal para descansar.'

In [25]:
import pandas as pd
import numpy as np

# Assuming you have a DataFrame named 'f' with a column named 'English_Text'
# Replace the sample data with your actual DataFrame

data = {'English_Text': f["English_Text"].tolist()}
df = pd.DataFrame(data)

# Function to clean the text
def clean_text(text):
    if pd.notna(text):  # Check for NaN values
        # Remove "(Translated by Google)"
        text = text.replace('(Translated by Google)', '')

        # Remove "\n\n(Original)\n"
        text = text.replace('\n\n(Original)\n', '')

        # Remove "\" 
        text = text.replace('\\', '')

        return text.strip()  # Remove leading and trailing whitespaces
    else:
        return text  # Return NaN if the input is NaN

# Apply the cleaning function to each row in the 'English_Text' column
df['cleaned_text'] = df['English_Text'].apply(clean_text)

# Display the DataFrame with the cleaned text
print(df)

                                         English_Text  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
..                                                ...
71  (Translated by Google) Great food.. cozy place...
72  (Translated by Google) Just wonderful. Good pr...
73  (Translated by Google) Very good\n\n(Original)...
74  (Translated by Google) The best\n\n(Original)\...
75  (Translated by Google) Very quiet and wonderfu...

                                         cleaned_text
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
..                                                ...
71  Great food.. cozy placeComida ótima.. lugar ac...
72  Just wonderful. Good price, good restaurant to...
73                                 Very goodMuito boa
74                                   The bestO melhor
75  Very quiet and wonderful family placeLocal mui...

[76 rows x 2 columns]

In [27]:
df.head(50)

,English_Text,cleaned_text
0,NaN,NaN
1,NaN,NaN
2,NaN,NaN
3,NaN,NaN
4,NaN,NaN
5,NaN,NaN
6,NaN,NaN
7,NaN,NaN
8,NaN,NaN
9,NaN,NaN
10,NaN,NaN
11,NaN,NaN
12,NaN,NaN
13,NaN,NaN
14,NaN,NaN
15,NaN,NaN
16,NaN,NaN
17,NaN,NaN
18,NaN,NaN
19,NaN,NaN
20,NaN,NaN
21,NaN,NaN
22,NaN,NaN
23,NaN,NaN
24,NaN,NaN
25,(Translated by Google) Camping with a family a...,Camping with a family atmosphere and good stru...
26,NaN,NaN
27,NaN,NaN
28,(Translated by Google) The best camping I've e...,The best camping I've ever been to! Very cool ...
29,(Translated by Google) Very good\n\n(Original)...,Very goodMuito bom
30,NaN,NaN
31,(Translated by Google) Best infrastructure for...,"Best infrastructure for campers in the region,..."
32,(Translated by Google) Very family place. Alwa...,Very family place. Always very pleasant and un...
33,NaN,NaN
34,"(Translated by Google) Great place to camp, or...","Great place to camp, or stay in great cabins w..."
35,NaN,NaN
36,(Translated by Google) Excellent\n\n(Original)...,ExcellentÓtimo
37,(Translated by Google) Crowded!! It had everyt...,Crowded!! It had everything to be good. Dirty ...
38,Top,Top
39,"(Translated by Google) Great facilities, good ...","Great facilities, good trails, restaurant, etc..."
40,(Translated by Google) The atmosphere is very ...,"The atmosphere is very familiar, the food is v..."
41,NaN,NaN
42,(Translated by Google) We liked a lot\n\n(Orig...,We liked a lotGostamos muito
43,NaN,NaN
44,NaN,NaN
45,NaN,NaN
46,(Translated by Google) Ideal place to rest.\n\...,Ideal place to rest.Lugar ideal para descansar.
47,(Translated by Google) I based on the reviews ...,"I based on the reviews to choose the inn, but ..."
48,NaN,NaN
49,(Translated by Google) Cozy....I really like t...,Cozy....I really like the place and the staff!...

In [28]:
df["cleaned_text"].iloc[46]

'Ideal place to rest.Lugar ideal para descansar.'

In [33]:
import pandas as pd
from langdetect import detect

# Assuming you have a DataFrame df with a column named 'cleaned_text'
df = pd.DataFrame({'cleaned_text': df["cleaned_text"]})
    
# Function to detect language
def detect_language(text):
    try:
        lang = detect(text)
        return lang
    except:
        return 'unknown'

# Apply language detection to each row in the 'cleaned_text' column
df['Language'] = df['cleaned_text'].apply(detect_language)

# Separate into different columns based on language
df['English_Text'] = df[df['Language'] == 'en']['cleaned_text']
df['Portuguese_Text'] = df[df['Language'] == 'pt']['cleaned_text']

# Drop the 'Language' column if you no longer need it
df = df.drop(columns=['Language'])

# Display the results
print("DataFrame with English and Portuguese Texts:")
print(df)

KeyError: 'cleaned_text'